CREATE DATABASE NetCoreDB;

USE NetCoreDB;

CREATE TABLE Usuarios(
	ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	USERNAME  VARCHAR(25) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO VARCHAR(40) NOT NULL
);

CREATE TABLE ARTICULOS(
	ID_ARTICULO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRECIO DECIMAL NOT NULL
);


